import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import React from 'react';

import './globals.css';
import { Navbar } from '@/components/navbar';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { NextUIProvider } from '@nextui-org/react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <NextUIProvider>
          <AppRouterCacheProvider>{children}</AppRouterCacheProvider>
        </NextUIProvider>
      </body>
    </html>
  );
}
